// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlEM-GbfW0_HAtOrdqEbt6QDibSWd1IB0',
    appId: '1:500503077729:web:d51d65b06e532b4c259b20',
    messagingSenderId: '500503077729',
    projectId: 'flutter-firebase-analyti-af9bb',
    authDomain: 'flutter-firebase-analyti-af9bb.firebaseapp.com',
    storageBucket: 'flutter-firebase-analyti-af9bb.firebasestorage.app',
    measurementId: 'G-DESTJ1DD2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-JgZDJp3j954KoLGSo1alP4cyYHmQ9hs',
    appId: '1:500503077729:android:bd26cd9459ed07b0259b20',
    messagingSenderId: '500503077729',
    projectId: 'flutter-firebase-analyti-af9bb',
    storageBucket: 'flutter-firebase-analyti-af9bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp3ZcZse-ur_EW_JM3z8oAu-JPILG1gZY',
    appId: '1:500503077729:ios:8a39ac3ea36a9fab259b20',
    messagingSenderId: '500503077729',
    projectId: 'flutter-firebase-analyti-af9bb',
    storageBucket: 'flutter-firebase-analyti-af9bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterGoogleAnalyticsLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp3ZcZse-ur_EW_JM3z8oAu-JPILG1gZY',
    appId: '1:500503077729:ios:8a39ac3ea36a9fab259b20',
    messagingSenderId: '500503077729',
    projectId: 'flutter-firebase-analyti-af9bb',
    storageBucket: 'flutter-firebase-analyti-af9bb.firebasestorage.app',
    iosBundleId: 'com.example.flutterGoogleAnalyticsLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlEM-GbfW0_HAtOrdqEbt6QDibSWd1IB0',
    appId: '1:500503077729:web:d2e4f5e658696b5f259b20',
    messagingSenderId: '500503077729',
    projectId: 'flutter-firebase-analyti-af9bb',
    authDomain: 'flutter-firebase-analyti-af9bb.firebaseapp.com',
    storageBucket: 'flutter-firebase-analyti-af9bb.firebasestorage.app',
    measurementId: 'G-JZN9WYVB7F',
  );
}
